FROM node:current-alpine3.21

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

# Generate Prisma client
RUN npm run generate-prisma

# Build only the user-app
RUN npm run build --filter=user-app

CMD ["npm", "run", "start-user-app"]